[package]
name = "sudoku"
version = "0.1.0"
authors = ["nagarkamakshi"]
edition = "2018"

[dependencies]
rand = "0.6"
clap = "2.33.0"
piston = "0.43.0"
piston2d-opengl_graphics = "0.62.0"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
